flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

# New Post
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

# Home
@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.date_post.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

# About
@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

# New Blueprint Object
posts = Blueprint('posts', __name__)

# New Post
@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

# View Post
@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

# Update Post
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    # Authen
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

# Update Post
@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    # Authen
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

# New Blueprint Object
users = Blueprint('users', __name__)

# Register
@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():
        # hash user password
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        # new instance of user
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        flash('Your account has been created. You can now login!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)

# Login
@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # checking query
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', tiltle='Login', form=form)

# Logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# Account
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename=f'img/profile/{current_user.image_file}')
    return render_template('account.html', title='Account', image_file=image_file, form=form)

# View All Post For a Particular User
@users.route('/user/<string:username>')
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_post.desc()).paginate(page=page, per_page=5)
    return render_template('user_post.html', title='User Post', posts=posts, user=user)

# Password Reset('Email Require')
@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    # check if user is log in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been send with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)

# New Password
@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    # check if user is log in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    # Verify Token
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token.', 'info')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        # hash user password
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()

        flash('Your password has been updated!. You can now login!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends 'layout.html' %}

<!-- css -->
{% block css %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/index/index.css')}}"
/>{% endblock css %}

<!-- Body -->
{% block content %}
<div class="content-section">
  <div
    class="infogram-embed"
    data-id="8c0e1526-748f-4817-9d90-ca32d52fa06d"
    data-type="interactive"
    data-title="flaskblog"
  ></div>
  <script>
    !(function(e, t, s, i) {
      var n = "InfogramEmbeds",
        o = e.getElementsByTagName("script")[0],
        d = /^http:/.test(e.location) ? "http:" : "https:";
      if ((/^\/{2}/.test(i) && (i = d + i), window[n] && window[n].initialized))
        window[n].process && window[n].process();
      else if (!e.getElementById(s)) {
        var r = e.createElement("script");
        (r.async = 1), (r.id = s), (r.src = i), o.parentNode.insertBefore(r, o);
      }
    })(
      document,
      0,
      "infogram-async",
      "https://e.infogram.com/js/dist/embed-loader-min.js"
    );
  </script>
  <div
    style="padding:8px 0;font-family:Arial!important;font-size:13px!important;line-height:15px!important;text-align:center;border-top:1px solid #dadada;margin:0 30px"
  >
    <a
      href="https://infogram.com/8c0e1526-748f-4817-9d90-ca32d52fa06d"
      style="color:#989898!important;text-decoration:none!important;"
      target="_blank"
      >flaskblog</a
    ><br /><a
      href="https://infogram.com"
      style="color:#989898!important;text-decoration:none!important;"
      target="_blank"
      rel="nofollow"
      >Infogram</a
    >
  </div>
</div>
<!-- body -->
{% endblock content %}

<!-- Js -->
{% block js %} {% endblock js %}

flaskblog/templates/account.html
{% extends 'layout.html' %}
<!-- css -->
{% block css %}
<link rel="stylesheet" href="{{url_for('static',filename='css/account/account.css')}}">
{% endblock css %}

<!-- Body -->
{% block content %}
    <div class="account-section">
        <div class="media">
            <img src="{{image_file}}" alt="{{current_user.username}}" class="rounded-circle account-img">
            <div class="media-body">
                <h2 class="account-heading">{{current_user.username}}</h2>
                <p class="text-secondary">{{current_user.email}}</p>
            </div>
       
            <!-- From Here -->
            <div class="content-section">
                <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <h2 class="border-bottom mb-4">Account Info</h2>
                    <!-- Username -->
                    <div class="form-group">
                    {{ form.username.label(class='form-control-label')}}
            
                    {% if form.username.errors %}
                        {{form.username(class='form-control invalid')}}
                        <div class="invalid">
                            {% for error in form.username.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.username(class='form-control')}}
                    {% endif %}
                    </div>
            
                    <!-- Email -->
                    <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{form.email(class='form-control invalid')}}
                        <div class="invalid">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class='form-control')}}
                    {% endif %}
                    </div>

                    <!-- Picture -->
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class='form-control-file')}}
                        {% if form.picture.errors %}
                        <div class="invalid">
                            {% for error in form.picture.errors %}
                                <span>{{error}}</span> <br>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.submit(class='btn') }}
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h2 class="border-bottom mb-4">{{ legend }}</h2>

      <!-- title -->
      <div class="form-group">
        {{ form.title.label(class='form-control-label') }}
        {% if form.title.errors %}
        {{form.title(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.title(class='form-control')}}
        {% endif %}
      </div>

      <!-- content -->
      <div class="form-group">
        {{ form.content.label(class='form-control-label') }}
        {% if form.content.errors %}
        {{form.content(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.content(class='form-control')}}
        {% endif %}
      </div>

    </div>
    <div class="form-group">
      {{ form.submit(class='btn') }}
    </div>
  </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends 'layout.html' %} 

<!-- css -->
{% block css %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/index/index.css')}}"
/>{% endblock css %}

<!-- Body -->
{% block content %}
<section>
  {% for post in posts.items %}
  <article>
    <div class="article_name">
      <div>
          <img src="{{url_for('static', filename='img/profile/' + post.author.image_file)}}" alt="{{post.author.username}}">
          <a href="{{url_for('users.user_post', username=post.author.username)}}" title="{{ post.author.username }}">{{ post.author.username }}</a>
      </div>
      <small>{{ post.date_post.strftime('%B %d, %Y %I:%M %p') }}</small>
    </div>
    <div class="article_content">
      <h1>
        <a href="{{url_for('posts.post', post_id=post.id)}}" title="{{ post.title }}">{{ post.title }}</a>
      </h1>
      <p>{{ post.content }}</p>
    </div>
  </article>
  {% endfor %}
</section>
<div class="pagination">
  {% for page_num in posts.iter_pages() %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="links current" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
      {% else %}
        <a class="links" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
      {% endif %}
    {% else %}
      <span>...</span>
    {% endif %}
  {% endfor %}
</div>
<!-- body -->
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <!-- css -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/form.css')}}"
    />
    
    {% block css %} {% endblock css %}

    <!-- title -->
    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
  </head>

  <body>
    <header>
      <nav>
        <!-- left Col -->
        <div class="col_left">
          {% if current_user.is_authenticated %}
            <h3>Flask Blog | {{current_user.username}}</h3>
          {% else %}
            <h3>Flask Blog</h3>
          {% endif %}
          <ul>
            <li><a href="{{url_for('main.home')}}">Home</a></li>
            <li><a href="{{url_for('main.about')}}">About</a></li>
          </ul>
        </div>

        <!-- Right Col -->
        <div class="col_right">
          <ul>
          {% if current_user.is_authenticated %}
            <li><a href="{{url_for('posts.new_post')}}">New Post</a></li>
            <li><a href="{{url_for('users.account')}}">Account</a></li>
            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
          {% else %}
            <li><a href="{{url_for('users.login')}}">Login</a></li>
            <li><a href="{{url_for('users.register')}}">Register</a></li>
          {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <!-- Body -->
    <main>
      <div class="main_wrapper">
   
        <!-- Left -->
        <div class="col_left">
           <!-- flash messages -->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert {{category}}">
                  <p>{{message}}</p>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %} {% endblock content %}
        </div>

        <!-- Right -->
        <div class="col_right">
          <h2>Updates</h2>
          <p>You can put a bunch of stuff here.</p>
          <ul>
            <li>Latest Blog</li>
            <li>Advert</li>
            <li>Comments</li>
          </ul>
        </div>
      </div>
    </main>

    <!-- Js -->
    {% block js %} {% endblock js %}
  </body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}
<!-- css -->
{% block css %} {% endblock css %}
<!-- Body -->
{% block content %}

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h2 class="border-bottom mb-4">Login</h2>

      <!-- Email -->
      <div class="form-group">
        {{ form.email.label(class='form-control-label') }}
        {% if form.email.errors %}
        {{form.email(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.email(class='form-control')}}
        {% endif %}
      </div>

      <!-- Password -->
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {% if form.password.errors %}
        {{form.password(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.password(class='form-control')}}
        {% endif %}
      </div>

      <!-- Remember -->
      <div class="form-check">
        {{form.remember(class="check")}}
        {{form.remember.label(class="check")}}
      </div>
    </div>
    <div class="form-group">
      {{ form.submit(class='btn') }}
    </div>
    <small class="fg-pass"><a href="{{url_for('users.reset_request')}}">Forgot Password?</a></small>
  </form>
</div>
<hr class="hr-line" />

<small class="small-help"
  >Need An Account? <a href="{{ url_for('users.register') }}">Sign up now</a></small
>
{% endblock content %}

flaskblog/templates/post.html
{% extends 'layout.html' %}

<!-- css -->
{% block css %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/index/index.css')}}"
/>{% endblock css %}

<!-- Body -->
{% block content %}
<section>
  <article>
    <div class="article_name">
      <div>
        <img
          src="{{url_for('static', filename='img/profile/' + post.author.image_file)}}"
          alt="{{ post.author.username }}"
        />
        <a
          href="{{url_for('users.user_post', username=post.author.username)}}"
          title="{{ post.author }}"
          >{{ post.author.username }}</a
        >
      </div>
      <small>{{ post.date_post.strftime("%B %d, %Y") }}</small>
    </div>
    <div class="article_content">
      <h2>{{ post.title }}</h2>
      <p>{{ post.content }}</p>
    </div>
    {% if post.author == current_user %}
    <div class="update_post">
      <a href="{{url_for('posts.update_post', post_id=post.id)}}">Edit Post</a>
      <button class="del">Delete</button>
    </div>
    {% endif %}
  </article>
</section>
<!-- body -->
{% endblock content %}

<!-- Js -->
{% block js %}
<script>
  function create_element(name, class_name) {
    let element = document.createElement(name);
    element.className = "" + class_name;
    return element;
  }

  function close_div() {
    let body = document.querySelector("body");
    body.removeChild(body.firstElementChild);
  }

  let d = document.querySelector(".update_post .del");
  d.addEventListener("click", () => {
    let div = create_element("div", "confirm_del");
    let div_wrapper = create_element("div", "confirm_del_wrapper");
    let message_blog = create_element("div", "message_blog");
    let h2 = create_element("h2", "alert_title");
    h2.innerText = "Confirm Delete";
    let p = create_element("p", "alert_content");
    p.innerText = "Are you sure you want to delete this post?";

    let buttons = create_element("div", "alert_buttons");
    let no = create_element("button", "alert_btn");
    no.innerHTML = "No";

    no.addEventListener("click", () => {
      close_div();
    });

    // Form
    var f = document.createElement("form");
    f.setAttribute("method", "POST");
    f.setAttribute("action", "{{url_for('posts.delete_post', post_id=post.id)}}");
    var s = create_element("input", "alert_btn alert_yes"); //input element, Submit button
    s.setAttribute("type", "submit");
    s.setAttribute("value", "Delete");
    f.appendChild(s);

    buttons.appendChild(no);
    buttons.appendChild(f);

    message_blog.appendChild(h2);
    message_blog.appendChild(p);
    message_blog.appendChild(buttons);
    div_wrapper.appendChild(message_blog);
    div.appendChild(div_wrapper);
    document.body.insertBefore(div, document.querySelector("header"));
  });
</script>
{% endblock js %}

flaskblog/templates/register.html
{% extends 'layout.html' %}
<!-- css -->
{% block css %} {% endblock css %}
<!-- Body -->
{% block content %}

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h2 class="border-bottom mb-4">Join Today</h2>
      <!-- Username -->
      <div class="form-group">
        {{ form.username.label(class='form-control-label')}}

        {% if form.username.errors %}
            {{form.username(class='form-control invalid')}}
            <div class="invalid">
                {% for error in form.username.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.username(class='form-control')}}
        {% endif %}
      </div>

      <!-- Email -->
      <div class="form-group">
        {{ form.email.label(class='form-control-label') }}
        {% if form.email.errors %}
            {{form.email(class='form-control invalid')}}
            <div class="invalid">
                {% for error in form.email.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.email(class='form-control')}}
        {% endif %}
      </div>

      <!-- Password -->
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {% if form.password.errors %}
            {{form.password(class='form-control invalid')}}
            <div class="invalid">
                {% for error in form.password.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.password(class='form-control')}}
        {% endif %}
      </div>

      <!-- Confirm Password -->
      <div class="form-group">
        {{ form.confirm_password.label(class='form-control-label') }}
        {% if form.confirm_password.errors %}
            {{form.confirm_password(class='form-control invalid')}}
            <div class="invalid">
                {% for error in form.confirm_password.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.confirm_password(class='form-control')}}
        {% endif %}
      </div>
    </div>
    <div class="form-group">
      {{ form.submit(class='btn') }}
    </div>
  </form>
</div>
<hr class='hr-line'/>

<small class="small-help"
  >Already Have An Account?
  <a href="{{ url_for('users.login') }}">Sign in</a></small
>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends 'layout.html' %}
<!-- css -->
{% block css %} {% endblock css %}
<!-- Body -->
{% block content %}

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h2 class="border-bottom mb-4">Reset Password</h2>

      <!-- Email -->
      <div class="form-group">
        {{ form.email.label(class='form-control-label') }}
        {% if form.email.errors %}
        {{form.email(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.email(class='form-control')}}
        {% endif %}
      </div>
    </div>
    <div class="form-group">
      {{ form.submit(class='btn') }}
    </div>
  </form>
</div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends 'layout.html' %}
<!-- css -->
{% block css %} {% endblock css %}
<!-- Body -->
{% block content %}

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <h2 class="border-bottom mb-4">Reset Password</h2>

      <!-- Password -->
      <div class="form-group">
        {{ form.password.label(class='form-control-label') }}
        {% if form.password.errors %}
        {{form.password(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.password(class='form-control')}}
        {% endif %}
      </div>
      
      <!-- confirm_Password -->
      <div class="form-group">
        {{ form.confirm_password.label(class='form-control-label') }}
        {% if form.confirm_password.errors %}
        {{form.confirm_password(class='form-control invalid')}}
        <div class="invalid">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{form.confirm_password(class='form-control')}}
        {% endif %}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class='btn') }}
    </div>
  </form>
</div>
{% endblock content %}

flaskblog/templates/user_post.html
{% extends 'layout.html' %} 

<!-- css -->
{% block css %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/index/index.css')}}"
/>{% endblock css %}

<!-- Body -->
{% block content %}
<section>
    <h1 class="username">Post by {{user.username}} ({{posts.total}})</h1>
  {% for post in posts.items %}
  <article>
    <div class="article_name">
      <div>
          <img src="{{url_for('static', filename='img/profile/' + post.author.image_file)}}" alt="{{post.author.username}}">
          <a href="{{url_for('users.user_post', username=post.author.username)}}" title="{{ post.author.username }}">{{ post.author.username }}</a>
      </div>
      <small>{{ post.date_post.strftime('%B %d, %Y %I:%M %p') }}</small>
    </div>
    <div class="article_content">
      <h1>
        <a href="{{url_for('posts.post', post_id=post.id)}}" title="{{ post.title }}">{{ post.title }}</a>
      </h1>
      <p>{{ post.content }}</p>
    </div>
  </article>
  {% endfor %}
</section>
<div class="pagination">
  {% for page_num in posts.iter_pages() %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="links current" href="{{url_for('users.user_post', username=user.username, page=page_num)}}">{{page_num}}</a>
      {% else %}
        <a class="links" href="{{url_for('users.user_post', username=user.username, page=page_num)}}">{{page_num}}</a>
      {% endif %}
    {% else %}
      <span>...</span>
    {% endif %}
  {% endfor %}
</div>
<!-- body -->
{% endblock content %}